# Generated by Django 5.0.2 on 2024-06-30 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('admin_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('admin_password', models.CharField(blank=True, max_length=128, null=True)),
                ('admin_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('admin_address', models.TextField(blank=True, null=True)),
                ('admin_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
