# Generated by Django 5.0.2 on 2024-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_user',
            old_name='admin_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='admin_user',
            old_name='admin_created_at',
            new_name='customer_created_at',
        ),
        migrations.RenameField(
            model_name='admin_user',
            old_name='admin_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='admin_user',
            old_name='admin_password',
            new_name='customer_password',
        ),
        migrations.RenameField(
            model_name='admin_user',
            old_name='admin_phone_number',
            new_name='customer_phone_number',
        ),
        migrations.RenameField(
            model_name='admin_user',
            old_name='admin_user_id',
            new_name='customer_user_id',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='admin_email',
        ),
        migrations.AddField(
            model_name='admin_user',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
