# Generated by Django 5.0.2 on 2024-07-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_admin_address_admin_user_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_user',
            old_name='customer_user_id',
            new_name='customer_id',
        ),
    ]
