# Generated by Django 5.0.2 on 2024-06-26 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_Categorytype', models.CharField(blank=True, max_length=20, null=True)),
                ('main_Category', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Categorytype', models.CharField(blank=True, max_length=20, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=20, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('img1', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img2', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img3', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img4', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img5', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img6', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img7', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('img8', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active_product', models.BooleanField(blank=True, default=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('qty1', models.IntegerField(blank=True, default=0, null=True)),
                ('qty2', models.IntegerField(blank=True, default=0, null=True)),
                ('qty3', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensions (WxDxH)')),
                ('installation_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Installation Type')),
                ('storage_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Storage Capacity')),
                ('purification_modules', models.TextField(blank=True, null=True, verbose_name='Purification Modules')),
                ('input_water_pressure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Input Water Pressure')),
                ('input_water_temperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Input Water Temperature')),
                ('input_water_chlorine_max', models.CharField(blank=True, max_length=50, null=True, verbose_name='Input Water Chlorine (Max)')),
                ('input_water_tds', models.CharField(blank=True, max_length=50, null=True, verbose_name='Input Water TDS')),
                ('uv_lamp', models.CharField(blank=True, max_length=50, null=True, verbose_name='UV Lamp')),
                ('uv_lamp_life', models.CharField(blank=True, max_length=50, null=True, verbose_name='UV Lamp Life')),
                ('power_consumption', models.CharField(blank=True, default='Unknown', max_length=50, null=True, verbose_name='Power Consumption')),
                ('operating_input_voltage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating Input Voltage')),
                ('included_in_box', models.TextField(blank=True, null=True, verbose_name='Included in the Box')),
                ('product_warranty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Warranty')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.main_category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.sub_category')),
            ],
        ),
    ]
