# Generated by Django 5.0.2 on 2024-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='main_Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='main_Categorytype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Sub_Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Sub_Categorytype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
