# Generated by Django 5.0.2 on 2024-07-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_main_category_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
