# Generated by Django 5.0.2 on 2024-07-22 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subadmin',
            fields=[
                ('Sub_admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Sub_admin_name', models.CharField(max_length=100)),
                ('Sub_admin_email', models.EmailField(max_length=254)),
                ('Sub_admin_password', models.CharField(max_length=100)),
                ('Sub_admin_address', models.CharField(max_length=200)),
                ('Sub_admin_pincode', models.CharField(max_length=100)),
                ('Sub_admin_ac', models.CharField(max_length=100)),
                ('Sub_admin_ifc', models.CharField(max_length=100)),
                ('Sub_admin_no', models.CharField(max_length=100)),
                ('Sub_admin_2no', models.CharField(max_length=100)),
            ],
        ),
    ]
